# -*- coding: utf-8 -*-
"""CurrencyAPI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jrkx5WqHpROu6NE2OgtMmY66iBg79W16
"""

pip install requests dash dash-html-components dash-core-components

import requests
import dash
import dash_core_components as dcc
import dash_html_components as html

API_KEY = "3c3ec998a3c635f75aa0a127ce032730"
BASE_URL = f"http://data.fixer.io/api/latest?access_key={API_KEY}"

app = dash.Dash(__name__)

app.layout = html.Div(children=[
    html.H1("Real-Time Currency Exchange Rates"),
    html.Div("Base Currency:", style={"display": "inline-block", "width": "150px"}),
    dcc.Dropdown(
        id="base-currency",
        options=[{"label": c, "value": c} for c in ["USD", "EUR", "GBP", "JPY", "AUD"]],
        value="USD",
        style={"display": "inline-block", "width": "200px"},
    ),
    html.Br(),
    html.Div(id="exchange-rates", style={"margin-top": "20px"}),
])

from dash import Output
from dash import Input

@app.callback(
    Output("exchange-rates", "children"),
    Input("base-currency", "value"),
)
def update_rates(base_currency):
    try:
        response = requests.get(BASE_URL)
        data = response.json()
        rates = data["rates"]

        # Filter and format output
        output = [f"{rate_code}: {rate:.2f}" for rate_code, rate in rates.items() if rate_code != base_currency]
        return html.Div(output, style={"white-space": "pre"})
    except requests.exceptions.RequestException as e:
        return html.Div(f"Error retrieving data: {e}", style={"color": "red"})

# Run the app
if __name__ == "__main__":
    app.run_server(debug=True)